### ISSUE TITLE
Error in Dashboard view: TypeError: values is null  / slimstat.admin.js:499:8

### ISSUE THREAD

**Issue by brianmccrory** [slimstat/wp-slimstat#1]
Possibly an error arising from the latest update to slimstat.admin.js?

The "Screen Options" and "Help" links don't respond, as well as slimstat modules on the Dashboards page.

TypeError: values is null   [Learn More]    slimstat.admin.js:499:8

Inspect Element -> Console shows (URL details omitted):

	get_current_tab [...]/wp-slimstat/admin/js/slimstat.admin.js:499:8
	<anonymous> [...]/wp-slimstat/admin/js/slimstat.admin.js:190:54
	i [...]/wp-admin/load-scripts.php:2:27444
	fireWith [...]/wp-admin/load-scripts.php:2:28213
	ready [...]/wp-admin/load-scripts.php:2:30004
	K [...]/wp-admin/load-scripts.php:2:30366

Line 499 in my source (latest update) is in the get_current_tab function:
		if ( typeof values[ 2 ] == 'string' ) {

**Comment by slimstat** [comment]
This is being looked into. Thank you for pointing it out. Feel free to test the updated code, once we push it to github, and to report back!

**Comment by brianmccrory** [comment]
Thank you, that did it! Tested the change with the new files and my Dashboard is back in business. 
I appreciate the quick turnaround!

**Comment by slimstat** [comment]
Please consider writing a review for Slimstat as a token of appreciation for the support you received. It would be a nice way to say thank you and to let people know how much you value this plugin:

https://wordpress.org/support/plugin/wp-slimstat/reviews/#new-post
