### ISSUE TITLE
Opt-out problems with one pager sites

### ISSUE THREAD

**Issue by boehmviskom** [slimstat/wp-slimstat#2]
Hey guys,

using the opt-out link option can cause problems with the navigation on one pager websites. Take my site as an example: http://stephan.boehm.agency/

When you build a menu for one pagers you'll link the page in the menu and add anchors (e.g. #projekte) for your page sections to each of the menu items. By clicking e.g. "accept" on the opt-out pop-up you'll be linked to http://stephan.boehm.agency/?slimstat-opt-out=false. When you click on a menu item now, you'll be brought back to http://stephan.boehm.agency/#projekte. So, the page has to fully reload and then jumps to the desired location. Is there a way to go around this?

In some cases this causes a loop for the opt-out popup esp. when you visit the site inside an app like Instagram. The popup will load again, every time a visitor clicks on a menu item or visits one of the project items. Any ideas?

**Comment by slimstat** [comment]
Hi there, 

would you mind testing the latest commit to see if it solves your problem?

Thank you,
Jason #

**Comment by boehmviskom** [comment]
We found another workaround by using a third party cookie. We're using GDPR Cookie Consent for the banner now.
