### ISSUE TITLE
Article about GDPR plugins (e.g. Complianz)

### ISSUE THREAD

**Issue by robertoschwald** [slimstat/wp-slimstat#20]
Would be great if you could add this to the knowledge base (https://slimstat.freshdesk.com/support/home)

# Integration with GDPR banner plugins
To integrate Slimstat with GDPR cookie banner plugins to control usage of the slimstat cookie, you can set the Opt-Out Cookies / Opt-In Cookies settings accordinghly. With this you can control when the slimstat tracking cookie will be added / removed  in users' browser based on the settings the user select within the cookie banner.

## Example for Complianz Plugin
To control tracking behavior when using the Complianz plugin, add this settings to the Slimstat Tracker settings:
* Opt-Out-Cookies settings: cmplz_statistics=deny, complianz_consent_status=deny
* Opt-In Cookies settings: cmplz_statistics=allow

If you want to automatically remove the slimstat cookie if the user changes the cookie banner settings to deny / deny statistics, you can add a Complianz mu-plugin script. See [reload-after-consent.php ](https://github.com/Really-Simple-Plugins/complianz-integrations/blob/master/reload-after-consent.php). Add this script to wp-content/mu-plugins in your WP installation.

**Comment by robertoschwald** [comment]
See https://wordpress.org/support/topic/reload-page-after-statistics-consent-accept/ for details.

**Comment by slimstat** [comment]
Thank you, Robert. We just launched our redesigned website, and are working on migrating the documentation back to the main site, with filters etc.

**Comment by mostafasoufi** [comment]
Hey,

Thank you, Robert, added in the document https://wp-slimstat.com/resources/how-to-integrate-with-gdpr-banner-plugins/

Best.
