### ISSUE TITLE
Overview (Top Referring Domains) link issue

### ISSUE THREAD

**Issue by s7ech** [slimstat/wp-slimstat#21]
Hello,

when I view Top Referring Domains statistics from the overview and click on the "Open in new window" icon, the link opens like that "https://my-site.com/wp-admin/google.co.uk" instead of opening the site from which the visit comes directly.

It therefore sends me to a 404 page and I have to manually delete the half of the URL address each time if I want to visit. 

Kind regards

**Comment by slimstat** [comment]
Thank you for reporting this in Github. A fix will be added to the next release. We usually push it to this Git repo a few days before it goes live on the WP repo, so you're more than welcome to test it when it's out.
