### ISSUE TITLE
Translations for Add-Ons page

### ISSUE THREAD

**Issue by robertoschwald** [slimstat/wp-slimstat#25]
The texts of the Add-ons page table cannot be translated.

**Comment by slimstat** [comment]
Hi Robert, do you mean the strings "License Key" and "Price" in addons.php ? Everything else is coming from the Slimstat server (including the description). Glad to look into it...

**Comment by robertoschwald** [comment]
I mean "Version", "Price" and the description texts. Probably "License Key" as well, but as I do not have any license keys, yet, I can't see this text. 



![addons_de](https://user-images.githubusercontent.com/1519879/159186976-e3a44fe0-b0b4-4f78-8bd8-f906537bcbfd.png)

**Comment by robertoschwald** [comment]
Maybe it's possible to just send text keys from the server and replace with translated text in the plugin settings page?

**Comment by mostafasoufi** [comment]
Since the Add-Ons are in a separate plugin now, we can close this issue because everything is working fine.

Btw, I also updated the POT file.

Cheers!
