### ISSUE TITLE
Clicking on `mailto:` triggers an error in the ajax tracker in Slimstat on PHP 8.0

### ISSUE THREAD

**Issue by Juje** [slimstat/wp-slimstat#30]
**Problem**
After updating to PHP 8.0 Slimstat started posting a lot of errors and one of them happened on this line: https://github.com/slimstat/wp-slimstat/blob/master/wp-slimstat.php#L230 with the message `Undefined array key "host"`. The error happens when a user clicks on a `mailto:` link.

**Fix**
I'm not entirely sure what should be done to fix this because it could be handled or added like a download link.

FYI: All the rest seems to work perfectly in PHP 8.0 as far as I can see.

**Comment by mostafasoufi** [comment]
Apologies for the delayed response. We've implemented numerous compatibility fixes for PHP version 8.*, which should resolve the issue you encountered. Could you please test it again and let us know if everything is working as expected? Your feedback would be greatly appreciated.

Best
