### ISSUE TITLE
I would be interested in taking over this plugin

### ISSUE THREAD

**Issue by wolffe** [slimstat/wp-slimstat#31]
I would be interested in taking over this plugin. What do you need from me?

I already have an analytics plugin - Active Analytics - https://getbutterfly.com/wordpress-plugins/active-analytics/

I also managed/developer Smashing Analytics years ago - https://wordpress.org/plugins/smashing-analytics/

Best regards,
Ciprian

**Comment by mostafasoufi** [comment]
Thank you for opening the issue, this is already resolved.

Cheers
