### ISSUE TITLE
Fingerprinting2 options are not set correctly, leading to canvas and webgl fingerprinting

### ISSUE THREAD

**Issue by Level3Manatee** [slimstat/wp-slimstat#33]
The Fingerprint2 options in [wp-slimstat.js#L435](https://github.com/wp-slimstat/wp-slimstat/blob/f17b1b2a34802e612d69cc9f8f5aed5dbab6c0c1/wp-slimstat.js#L435) are never actually set, leading to full fingerprinting. In fact, the options need to be explicitly passed as the first parameter, as you can see in [fingerprint2.js#L1354](https://github.com/fingerprintjs/fingerprintjs/blob/577f251d18e3204b1420c45c50845f86d83cc946/fingerprint2.js#L1354).

This can be verified in Firefox by setting `privacy.resistFingerprinting` to `true`. Firefox will report that the site is attempting to use canvas fingerprinting.

The GDPR compliance of the various extended fingerprinting techniques are highly questionable (which I am guessing is why canvas and WebGL were set to be excluded in the first place).

Changing things to

```js
Fingerprint2.get( options, function ( components ) {
```

will _actually_ set the options, and Firefox will not report canvas fingerprinting anymore.

**Comment by mostafasoufi** [comment]
Ah, you're right, thank you for pointing it out and reporting it.

Fixed in the commit https://github.com/wp-slimstat/wp-slimstat/commit/07ae2cb66f1a8b4dad267545b08392b5df3432a3

Cheers!
