### ISSUE TITLE
Feature request: Fingerprinting options

### ISSUE THREAD

**Issue by Level3Manatee** [slimstat/wp-slimstat#34]
In wp-slimstat, Fingerprint2 is used to collect various information about visitors. Currently, the options are set to exclude
```js
var options = { excludes: { adBlock: true, addBehavior: true, userAgent: true, canvas: true, webgl: true } };
```
(at least once #33 is addressed)

However, a lot of additional information is still collected by the library and passed on to the server, leading to potential GDPR issues. See [here](https://github.com/fingerprintjs/fingerprintjs/blob/577f251d18e3204b1420c45c50845f86d83cc946/fingerprint2.js#L1314) for a full list of components that are trackable. By default, only `enumerateDevices`, `pixelRatio`,  `doNotTrack` and `fontsFlash` are turned off.

I would like to be able to configure these options from the backend, since I do not need most of these metrics and thus should not be collecting them in the first place for GDPR compliance. I would also like to deactivate calculating a fingerprint altogether.

For reference, these are the options I have added manually for now:
```var options = { excludes: { adBlock: true, addBehavior: true, userAgent: true, canvas: true, webgl: true, colorDepth: true, deviceMemory: true, hardwareConcurrency: true, sessionStorage: true, localStorage: true, indexedDb: true, addBehavior: true, openDatabase: true, cpuClass: true, plugins: true, webglVendorAndRenderer: true, hasLiedLanguages: true, hasLiedResolution: true, hasLiedOs: true, hasLiedBrowser: true, fonts: true, audio: true } };```

Of course, preferences and necessities may vary, which is why having the option to configure these would be great.

**Comment by mostafasoufi** [comment]
Hey,

Thank you for highlighting the importance of GDPR compatibility. I've incorporated those exclusions into the settings options. Regarding the latter point, we can enable modifications through WordPress JavaScript hooks or directly from the settings page.

Cheers!

**Comment by Level3Manatee** [comment]
Thanks.

I think modifications through the settings page would be the most accessible option, but given that all those data points were never visible through the normal analytics interface anyway, a hook would probably suffice.

**Comment by mostafasoufi** [comment]
Yeah, fair enough!

Best
