### ISSUE TITLE
Visitor missing from slimstat

### ISSUE THREAD

**Issue by blackPantherOS** [slimstat/wp-slimstat#37]
How it possible that a visitor IP and events missing from slimstat's log?  Visit only show in Apache access log. The visit time it was  ~8minutes.

This is bug or the visitor use something blocker?

**Comment by mostafasoufi** [comment]
Most-likely they are robots if SlimStat is not tracking them.

**Comment by blackPantherOS** [comment]
These the missing visitors not a bots. Look this ! 

**Example today happend again, In the server log show:**

`xx.xxx.xxx. **142**  - - [21/May/2023:18:26:32 +0200] "GET /tudasbazis/category/altalanos/biztonsag/page/3/ HTTP/1.1" 200 32548 "............./" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.
`

**This Linux desktop completely missing from Slimstat! **

![2023-05-21_20-36](https://github.com/wp-slimstat/wp-slimstat/assets/12883566/7e56d744-ea4f-40da-bf4f-44f488e3064a)


**This user is a returning visitor. I tried to find this visitor IP address in Slimstat and found a match for this address in April, his first visit to us from a Windows PC, but I found in server access log many many visit time from Linux PC as well! These records are missing in slimstat! The last visit time is 07:56 min was**

(by the way some bots show in slimstat, ex.: FB's bot)
