### ISSUE TITLE
Serious error with EC Plug-in "welcart" on Version 5.

### ISSUE THREAD

**Issue by signifiant** [slimstat/wp-slimstat#38]
I have serious error with EC Plug-in "welcart" when I did output welcart data on Ver. 5.
I checked with Ver. 4.9, it was no problem.
Wordpress tell me the follow error message. 

WordPress Version 6.2.2
Current Theme: Simplicity2 child (Version 20161002)
Current Plug-in: Slimstat Analytics (Version 5.0.5.1)
PHP Version 8.0.28

Error details
===============
Error Type E_ERROR in /home/**********/www/wordpress/wp-content/plugins/wp-slimstat/admin/index.php at file line 215.  Error Message: Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /home/classicus/www/wordpress/wp-content/plugins/wp-slimstat/admin/index.php:215
Stack trace:
#0 /home/**********/www/wordpress/wp-content/plugins/wp-slimstat/admin/index.php(215): strpos()
#1 /home/**********/www/wordpress/wp-includes/class-wp-hook.php(308): wp_slimstat_admin::init()
#2 /home/**********/www/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /home/**********/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/**********/www/wordpress/wp-settings.php(623): do_action()
#5 /home/**********/www/wordpress/wp-config.php(87): require_once('...')
#6 /home/**********/www/wordpress/wp-load.php(50): require_once('...')
#7 /home/**********/www/wordpress/wp-admin/admin.php(34): require_once('...')
#8 {main}
  thrown

I  would like to know if it is possible to avoid this problem.
Thank you.

**Comment by ighorbani** [comment]
Hi,

Thank you for reporting the issue, I will fix it in the following days. Could you please just send me the link of EC plugin Version 4.9, 5).

**Comment by mostafasoufi** [comment]
Fixed in this commit https://github.com/wp-slimstat/wp-slimstat/commit/829e33cd90f8a4afe2a7e9c5eed8fd618cfe591d

Thank you!
