### ISSUE TITLE
Bug: Authors with "." in their username can't view their statistics

### ISSUE THREAD

**Issue by tsunamicroissant** [slimstat/wp-slimstat#41]
When a post is viewed, a statistic entry is inserted into the database, containing the author of the viewed post. If you restrict authors to only seeing the statistics of their own posts, the statistic for them will be calculated from the database entries, where their username matches the "author" field in the database.

While writing the statistic, the author username is sanitized like a URL - e.g. "author.1" becomes "author-1" in the database.
When loading the statistic for the specific author, this sanitation seems not to be made. In consequence "author.1" will see no statistics.
When changing the "author" field entry in the database from "author-1" to "author.1", the statistic will be shown for the author.

Steps to reproduce:
- use a fresh wordpress installation (e.g. Docker: wordpress:6.2.0-php8.2-apache + mysql:latest)
- install plugin Slimstat
- configure: Slimstat -> Settings -> Access Control -> Restrict Authors -> yes (should be default)
- configure: Slimstat -> Settings -> Access Control -> Minimum Capability -> read
- create user "author.1"
- create post with user "author.1" as author
- view post when not being logged in
- check database table wp_slim_stats: "author-1" will be the author of the post view
- check slimstat overview as admin: the post will be listed in statistics
- check slimstat overview as "author.1": it will say "No data to display"

- (in database table wp_slim_stats: change author "author-1" to "author.1")
- (check slimstat overview as "author.1": the post will be listed in statistics)

Assumed Fix:
- sanitize usernames in the same way for both, writing and reading statistics

**Comment by mostafasoufi** [comment]
Thank you for reporting the issue, I'll assign this to our development team to fix it.

Cheers

**Comment by bluebyte1985** [comment]
Dear mostafa,

I hope this message finds you well. I wanted to kindly inquire if there have been any updates regarding this bugfix. I understand that resolving such issues can sometimes be complex, and I appreciate your team's efforts in addressing this matter.

If there have been any developments or if you require any additional information from our end to expedite the process, please do not hesitate to let us know. 

Thank you for your continued support and attention to this issue. We look forward to hearing from you soon.

Best regards

**Comment by mostafasoufi** [comment]
Hi @bluebyte1985 

Thank you for following-up, this will be fixed in the next version and will update you once is fixed.

Thanks

**Comment by ighorbani** [comment]
Dear @tsunamicroissant 
I am Iman, a member of VeronaLabs development team. **Your description is very helpful** for fix this issue. I will fix it. 

_Best_

**Comment by ighorbani** [comment]
Dear Users @bluebyte1985, @tsunamicroissant 

**This issue was fixed in this commit:** 
https://github.com/wp-slimstat/wp-slimstat/commit/39c88fdfe72de4ad14f49e1557fad8b57cedccd9

You can use from that in the next version of wp-slimstat plugin.

_Best
Iman Ghorbani_
