### ISSUE TITLE
Cross Site Scripting (XSS) reported for version <= 5.0.8

### ISSUE THREAD

**Issue by ArmReu** [slimstat/wp-slimstat#42]
https://patchstack.com/database/vulnerability/wp-slimstat/wordpress-slimstat-analytics-plugin-5-0-8-cross-site-scripting-xss-vulnerability?_a_id=110

**Comment by mostafasoufi** [comment]
Hello, we're already working on it and will be fixed soon.

**Comment by robertoschwald** [comment]
@mostafasoufi Can you elaborate why this ticket was closed without a commit? Fix in external resource?

**Comment by mostafasoufi** [comment]
@robertoschwald You're right but the task was actually created in our task management system. Once the commit is made and pushed, it will be linked to this issue.

**Comment by ighorbani** [comment]
Dear users @ArmReu @robertoschwald 
I am Iman a member of VeronaLabs Development team. We have fixed this issue. Here is the **[commit link](https://github.com/wp-slimstat/wp-slimstat/commit/d75d4b498004ce77355a580acb9222c82cbfe788)**.

Best
Iman Ghorbani
