### ISSUE TITLE
[Lost functionality] Export to other formats 

### ISSUE THREAD

**Issue by tdrivas** [slimstat/wp-slimstat#43]
Dear all,

Congrats for the great plugin. The last two months the **export feature** is not displayed on the wp dashboard. I dont know if it has been moved to the premium plan.  It is considered as a very useful feature. 

Thanks.
Best,
Thanassis

**Comment by mostafasoufi** [comment]
Hello,

Thank you for opening the issue, actually, yes, the export is moved to the Pro pack which will be released soon.

Cheers

**Comment by tdrivas** [comment]
Hi,

thanks for the clarification!

Best,
Thanassis
