### ISSUE TITLE
IPv6 anonymization does not appear GDPR compliant

### ISSUE THREAD

**Issue by Level3Manatee** [slimstat/wp-slimstat#47]
While reworking a privacy / data protection page (and subsequently looking at the SlimStat source code), I noticed that currently, IPv6 addresses only get their last field set to 0:

```php
// Do we need to anonymize this IP address?
if (self::$settings['anonymize_ip'] == 'on') {
    // IPv4 or IPv6
    $needle  = '.';
    $replace = '.0';
    if (self::_get_mask_length(self::$stat['ip']) == 128) {
        $needle  = ':';
        $replace = ':0000';
    }

    self::$stat['ip'] = substr(self::$stat['ip'], 0, strrpos(self::$stat['ip'], $needle)) . $replace;

    if (!empty(self::$stat['other_ip'])) {
        self::$stat['other_ip'] = substr(self::$stat['other_ip'], 0, strrpos(self::$stat['other_ip'], $needle)) . $replace;
    }
}
```
([wp-slimstat.php#L409](https://github.com/wp-slimstat/wp-slimstat/blob/f88cb002ae3f91dc10f1e4f8461567e455adf01a/wp-slimstat.php#L409C1-L424C10))

This is not even close to anonymization. Quoting from the [MediaWiki page on IP range blocks](https://www.mediawiki.org/wiki/Help:Range_blocks/IPv6):
> The most important fact to know about is that single or multiple /64 subnets for an end-user connection is a practical requirement of IPv6.

For GDPR compliance, Google Analytics (UA) zeroes the last 80 bits (!) of an IPv6 address ([source](https://support.google.com/analytics/answer/2763052?hl=en)). This appears to be the default for Matomo as well (see [issue from 2013](https://github.com/matomo-org/matomo/issues/3710#issuecomment-48310658)).

If I am not mistaken, this would correspond to the last 5 (!) groups getting set to 0 (see [matomo-org/component-network/src/IPv6.php#L44](https://github.com/matomo-org/component-network/blob/d31bde2f28d50b5417684cf64915d03aff29075a/src/IPv6.php#L44))

Please fix this asap, as the current status quo does not appear to comply with European law (I am not a lawyer, but as rules go, the requirement for IP anonymization is pretty clear afaik).

Please also fix the inadvertent fingerprinting that is currently happening, as outlined in issue #33, as this arguably is also not in accordance with European data protection regulation.

**Comment by mostafasoufi** [comment]
Hi @Level3Manatee,

Thanks for flagging this! based on your report, I switched to using the [wp_privacy_anonymize_ip()](https://developer.wordpress.org/reference/functions/wp_privacy_anonymize_ip/) function from WordPress in the commit https://github.com/wp-slimstat/wp-slimstat/commit/d22d0401cc7f9982b0b1db617b6bbe6de91f989d. It's neat for handling both IPv4 and IPv6 address anonymization. Here’s a quick rundown of how it works:

| Original IP                             	| Anonymized IP        	|
|-----------------------------------------	|----------------------	|
| 192.168.1.1                             	| 192.168.1.0          	|
| 10.190.27.70                            	| 10.190.27.0          	|
| 0897:D836:7A7C:803F:344B:5348:71EE:1130 	| 897:d836:7a7c:803f:: 	|
| 3ffe:1900:4545:3:200:f8ff:fe21:67cf     	| 3ffe:1900:4545:3::   	|
| fe80:0:0:0:200:f8ff:fe21:67cf           	| fe80::               	|

As for issue #33, I'm on it and will update soon.

Cheers!

**Comment by Level3Manatee** [comment]
Neat, did not know about that function. That does exactly what it should. Thanks!
