### ISSUE TITLE
MaxMind error: Access to undeclared static property wp_slimstat::$version

### ISSUE THREAD

**Issue by robertoschwald** [slimstat/wp-slimstat#49]
Newest version of Slimstat, when adding MaxMind License Key and enabling MaxMind, safe settings, boom.

Fatal error: Uncaught Error: Access to undeclared static property wp_slimstat::$version
in wp-content/plugins/wp-slimstat/vendor/maxmind.php on line 123

Call stack:

maxmind_geolite2_connector::download_url()
wp-content/plugins/wp-slimstat/vendor/maxmind.php:69
maxmind_geolite2_connector::download_maxmind_database()
wp-content/plugins/wp-slimstat/admin/config/index.php:657

**Comment by mostafasoufi** [comment]
Hey @robertoschwald 

This is already fixed in this https://github.com/wp-slimstat/wp-slimstat/commit/d85a74c73081f2454b82841c11365f0bb4c4c679 commit, going to release asap, thank you!
