### ISSUE TITLE
GeoIP downloader does not untar tar

### ISSUE THREAD

**Issue by Level3Manatee** [slimstat/wp-slimstat#52]
SlimStat Version 5.2.2

After setting the MaxMind License Key in the SlimStat settings, GeoIP functionality was not working. 
Error log:
```Slimstat Error - The MaxMind DB file's search tree is corrupt in [...]/wp-content/plugins/wp-slimstat/src/Utils/MaxMindReader.php on line 212```

Inspecting `/wp-content/uploads/wp-slimstat/GeoLite2-City.mmdb` revealed that it was in fact a tar archive file. After extracting it and replacing the file with the actual db, everything is working as expected.

**Comment by amirfallahii** [comment]
Hi @Level3Manatee 

Thank you for bringing this issue to our attention.

We have resolved this problem in the development version in the fb2a6f6bd8144161e1c069c5348e192f7efe18f8 commit, and we will soon release a new version of the plugin after final testing.

We appreciate your patience and cooperation.
Regards,
